[package]
name = "hinj"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = {version = "0.3.9", features = ["windef", "libloaderapi", "minwinbase","synchapi", "winuser", "memoryapi", "handleapi", "winbase", "winnt", "minwindef", "processthreadsapi", "tlhelp32"] }